# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: carla.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63\x61rla.proto\x12\x05\x63\x61rla\x1a\x1bgoogle/protobuf/empty.proto\"\x1b\n\x08\x41\x63torIds\x12\x0f\n\x07\x61\x63torId\x18\x01 \x03(\x05\"\x15\n\x06Number\x12\x0b\n\x03num\x18\x01 \x01(\x05\"y\n\x07Vehicle\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x1c\n\x05speed\x18\x02 \x01(\x0b\x32\r.carla.Vector\x12#\n\x0c\x61\x63\x63\x65leration\x18\x03 \x01(\x0b\x32\r.carla.Vector\x12\x1f\n\x08location\x18\x04 \x01(\x0b\x32\r.carla.Vector\")\n\x06Vector\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"4\n\x08Rotation\x12\r\n\x05pitch\x18\x01 \x01(\x01\x12\x0b\n\x03yaw\x18\x02 \x01(\x01\x12\x0c\n\x04roll\x18\x03 \x01(\x01\"O\n\tTransform\x12\x1f\n\x08location\x18\x01 \x01(\x0b\x32\r.carla.Vector\x12!\n\x08rotation\x18\x02 \x01(\x0b\x32\x0f.carla.Rotation2\xf5\x02\n\x0c\x43\x61rlaAdapter\x12\x44\n\x12\x45xecuteOneTimeStep\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\x38\n\x06\x46inish\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12>\n\x13GetManagedActorsIds\x12\x16.google.protobuf.Empty\x1a\x0f.carla.ActorIds\x12\x34\n\x13GetManagedActorById\x12\r.carla.Number\x1a\x0e.carla.Vehicle\x12.\n\rInsertVehicle\x12\x0e.carla.Vehicle\x1a\r.carla.Number\x12?\n\x13GetRandomSpawnPoint\x12\x16.google.protobuf.Empty\x1a\x10.carla.Transformb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'carla_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTORIDS._serialized_start=51
  _ACTORIDS._serialized_end=78
  _NUMBER._serialized_start=80
  _NUMBER._serialized_end=101
  _VEHICLE._serialized_start=103
  _VEHICLE._serialized_end=224
  _VECTOR._serialized_start=226
  _VECTOR._serialized_end=267
  _ROTATION._serialized_start=269
  _ROTATION._serialized_end=321
  _TRANSFORM._serialized_start=323
  _TRANSFORM._serialized_end=402
  _CARLAADAPTER._serialized_start=405
  _CARLAADAPTER._serialized_end=778
# @@protoc_insertion_point(module_scope)
